---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/aws-ia/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: b3e647e360f04623c6c582c12245fc92e20cc2e8  # frozen: v1.6.3
    hooks:
      - id: aws-ia-meta-hook
